In [4]:
import numpy as np

In [ ]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [ ]:
# Írj egy olyan fügvényt, ami megfordítja egy 2d array oszlopait. Bemenetként egy array-t vár.
# Be: [[1,2],[3,4]]
# Ki: [[2,1],[4,3]]
# column_swap()

In [17]:
def column_swap(arg):
  return np.fliplr(arg)
#column_swap(np.array([[1,2],[3,4]]))  

array([[2, 1],
       [4, 3]])

In [ ]:
# Készíts egy olyan függvényt ami összehasonlít két array-t és adjon vissza egy array-ben, hogy hol egyenlőek 
# Pl Be: [7,8,9], [9,8,7] 
# Ki: [1]
# compare_two_array()
# egyenlő elemszámúakra kell csak hogy működjön

In [ ]:
def compare_two_array(arr,arr2):
  res=np.array(arr[:]==arr2[:])
  return np.nonzero(res)[0]
#compare_two_array(np.array([7,8,9]), np.array([9,8,7]))

array([1])

In [ ]:
# Készíts egy olyan függvényt, ami vissza adja string-ként a megadott array dimenzióit:
# Be: [[1,2,3], [4,5,6]]
# Ki: "sor: 2, oszlop: 3, melyseg: 1"
# get_array_shape()
# 3D-vel még műküdnie kell!, 

In [ ]:
def get_array_shape(arr):
  return f"sor: {arr.shape[0]}, oszlop: {arr.shape[1]}, melyseg: {arr.ndim}"
#get_array_shape(np.array([[1,2,3], [4,5,6]]))

'sor: 2, oszlop: 3, melyseg: 2'

In [ ]:
# Készíts egy olyan függvényt, aminek segítségével elő tudod állítani egy neurális hálózat tanításához szükséges pred-et egy numpy array-ből. 
# Bementként add meg az array-t, illetve hogy mennyi class-od van. Kimenetként pedig adjon vissza egy 2d array-t, ahol a sorok az egyes elemek. Minden nullákkal teli legyen és csak ott álljon egyes, ahol a bementi tömb megjelöli. 
# Pl. ha 1 van a bemeneten és 4 classod van, akkor az adott sorban az array-ban a [1] helyen álljon egy 1-es, a többi helyen pedig 0.
# Be: [1, 2, 0, 3], 4
# Ki: [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# encode_Y()

In [16]:
def encode_Y(arr,c):
  return np.eye(c)[arr]
#encode_Y(np.array([1, 2, 0, 3]),4)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# A fenti feladatnak valósítsd meg a kiértékelését. Adj meg a 2d array-t és adj vissza a decodolt változatát
# Be:  [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# Ki:  [1, 2, 0, 3]
# decode_Y()

In [ ]:
def decode_Y(arr):
  return np.where(arr==1)[1]
#decode_Y(np.array([[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]))

array([1, 2, 0, 3])

In [ ]:
# Készíts egy olyan függvényt, ami képes kiértékelni egy neurális háló eredményét! Bemenetként egy listát és egy array-t és adja vissza azt az elemet, aminek a legnagyobb a valószínüsége(értéke) a listából.
# Be: ['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]. # Az ['alma', 'körte', 'szilva'] egy lista!
# Ki: 'szilva'
# eval_classification()

In [ ]:
def eval_classification(arr, prs):
  m=np.amax(prs)
  return arr[np.where(prs==m)[0][0]]
#eval_classification(['alma', 'körte', 'szilva'],np.array([0.2, 0.2, 0.6]))

'szilva'

In [ ]:
# Készíts egy olyan függvényt, ahol az 1D array-ben a páratlan számokat -1-re cseréli
# Be: [1,2,3,4,5,6]
# Ki: [-1,2,-1,4,-1,6]
# replace_odd_numbers()

In [ ]:
def replace_odd_numbers(arr):
  mask = np.mod(arr, 2) != 0
  arr[mask] = -1
  return arr
#replace_odd_numbers(np.array([1,2,3,4,5,6]))

[ True False  True False  True False]


array([-1,  2, -1,  4, -1,  6])

In [ ]:
# Készíts egy olyan függvényt, ami egy array értékeit -1 és 1-re változtatja, attól függően, hogy az adott elem nagyobb vagy kisebb a paraméterként megadott számnál.
# Ha a szám kisebb mint a megadott érték, akkor -1, ha nagyobb vagy egyenlő, akkor pedig 1.
# Be: [1, 2, 5, 0], 2
# Ki: [-1, 1, 1, -1]
# replace_by_value()

In [ ]:
def replace_by_value(arr,num):
  arr[arr<num]=-1
  arr[arr>=num]=1
  return arr
#replace_by_value(np.array([1, 2, 5, 0]),2)

[-1  2  5 -1]


array([-1,  1,  1, -1])

In [ ]:
# Készíts egy olyan függvényt, ami egy array értékeit összeszorozza és az eredményt visszaadja
# Be: [1,2,3,4]
# Ki: 24
# array_multi()
# Ha több dimenziós a tömb, akkor az egész tömb elemeinek szorzatával térjen vissza

In [ ]:
def array_multi(arr):
  return np.prod(arr)
#array_multi(np.array([1,2,3,4]))

24

In [ ]:
# Készíts egy olyan függvényt, ami egy 2D array értékeit összeszorozza és egy olyan array-el tér vissza, aminek az elemei a soroknak a szorzata
# Be: [[1, 2], [3, 4]]
# Ki: [2, 12]
# array_multi_2d()

In [ ]:
def array_multi_2d(arr):
  return np.prod(arr, axis=1)
#array_multi_2d(np.array([[1, 2], [3, 4]]))

array([ 2, 12])

In [ ]:
# Készíts egy olyan függvényt, amit egy meglévő numpy array-hez készít egy bordert nullásokkal. Bementként egy array-t várjon és kimenetként egy array jelenjen meg aminek van border-je
# Be: [[1,2],[3,4]]
# Ki: [[0,0,0,0],[0,1,2,0],[0,3,4,0],[0,0,0,0]]
# add_border()


In [ ]:
from numpy.core.multiarray import dtype
def add_border(arr):
  #before=np.insert(arr,0,np.array([0]),axis=1)  
  rowappend=np.column_stack([np.zeros(arr.shape[0],dtype=int),arr, np.zeros(arr.shape[0],dtype=int)])
  return np.vstack([np.zeros(rowappend.shape[1],dtype=int),rowappend,np.zeros(rowappend.shape[1],dtype=int) ])
#add_border(np.array([[1,2],[3,4]]))

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [ ]:
# A KÖTVETKEZŐ FELADATOKHOZ NÉZZÉTEK MEG A NUMPY DATA TYPE-JÁT!

In [ ]:
# Készíts egy olyan függvényt ami két dátum között felsorolja az összes napot és ezt adja vissza egy numpy array-ben. A fgv ként str vár paraméterként 'YYYY-MM' formában.
# Be: '2023-03', '2023-04'  # mind a kettő paraméter str.
# Ki: ['2023-03-01', '2023-03-02', .. , '2023-03-31',]
# list_days()

In [ ]:
def list_days(start_date,end_date): # to strinf needed
    sdate = np.datetime64(start_date)
    enddate= np.datetime64(end_date)

    # Create a range of dates between start and end dates
    dates= np.arange(start_date, end_date, dtype='datetime64[D]')
    return np.array(dates,dtype=str)
#list_days('2023-03', '2023-04')

array(['2023-03-01', '2023-03-02', '2023-03-03', '2023-03-04',
       '2023-03-05', '2023-03-06', '2023-03-07', '2023-03-08',
       '2023-03-09', '2023-03-10', '2023-03-11', '2023-03-12',
       '2023-03-13', '2023-03-14', '2023-03-15', '2023-03-16',
       '2023-03-17', '2023-03-18', '2023-03-19', '2023-03-20',
       '2023-03-21', '2023-03-22', '2023-03-23', '2023-03-24',
       '2023-03-25', '2023-03-26', '2023-03-27', '2023-03-28',
       '2023-03-29', '2023-03-30', '2023-03-31'], dtype='<U28')

In [ ]:
# Írj egy fügvényt ami vissza adja az aktuális dátumot az alábbi formában: YYYY-MM-DD. Térjen vissza egy 'numpy.datetime64' típussal.
# Be:
# Ki: 2017-03-24
# get_act_date()

In [ ]:
def get_act_date():
  return np.datetime64('today')
#get_act_date()


numpy.datetime64('2023-03-09')

In [ ]:
# Írj egy olyan függvényt ami visszadja, hogy mennyi másodperc telt el 1970 január 01. 00:02:00 óta. Int-el térjen vissza
# Be: 
# Ki: másodpercben az idó, int-é kasztolva
# sec_from_1970()

In [ ]:
def sec_from_1970():
  sdate = np.datetime64('1970-01-01T00:02:00')
  cdate = np.datetime64('now')
  secs = (cdate - sdate) / np.timedelta64(1, 's')
  return int(secs)
#sec_from_1970()

1678382023